apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alicloud-controller-manager
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: alicloud-controller-manager
    spec:
      dnsPolicy: Default
      tolerations:
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          value: "true"
          effect: "NoSchedule"
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/kube-test/alicloud-controller-manager:v0.1.0
        name: alicloud-controller-manager
        command:
          - /alicloud-controller-manager
          - --leader-elect=false
          - --allocate-node-cidrs=true
          - --cluster-cidr=172.17.6.0/24
          - --master=172.17.48.1:8080
        env:
          - name: ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: alicloud-config
                key: access-key-id
          - name: ACCESS_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: alicloud-config
                key: access-key-secret





