apiVersion: v1
kind: Service
metadata:
  name: zookeeper-master
  labels:
    app: zookeeper-master
  namespace: kube-system
spec:
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: main-port
  selector:
    app: zookeeper-master
  type: LoadBalancer

